; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = cansat_m7

[env:cansat_m7]
platform = ststm32
board = portenta_h7_m7
framework = arduino
build_src_filter = +<cansat_m7/*>
lib_deps = 
	arduino-libraries/MKRWAN@^1.1.2
	mikalhart/TinyGPSPlus@^1.0.3
	arduino-libraries/Servo@^1.2.2
	arduino-libraries/Arduino_BHY2Host@^1.0.9
	arduino-libraries/ArduinoBLE@^2.0.0	

[env:cansat_m4]
platform = ststm32
board = portenta_h7_m4
framework = arduino
build_src_filter = +<cansat_m4/*>

[env:groundstation_1310]
platform = atmelsam
board = mkrwan1310
framework = arduino
build_src_filter = +<groundstation_1310/*>
lib_deps = jgromes/RadioLib@^7.6.0
